#include "kr3d.h"
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

typedef struct { kr3d_vertex *v; uint32_t *i; size_t nv,ni; } mesh;
typedef struct { uint32_t *p; uint32_t w,h; kr3d_filter filter; kr3d_address au,av; } texture;
typedef struct { kr3d_texture_handle tex; uint32_t rgba,flags; kr3d_alpha_mode alpha; float cutoff; } material;
struct kr3d_device { mesh *meshes; texture *textures; material *materials; uint32_t nm,nt,nmat;
    uint32_t mw,mh; bool frame; kr3d_frame_desc f; uint32_t *owned_color; float *owned_depth;
    uint32_t submitted,rasterized,pixels; };
typedef struct { float x,y,z,w,u,v; kr3d_vec3 n; float c[4]; } cv;

static bool fail(kr3d_error *e,kr3d_error_code c,const char*s){if(e){e->code=c;(void)snprintf(e->message,sizeof e->message,"%s",s);}return false;}
static bool finite_mat(kr3d_mat4 m){for(int i=0;i<16;i++)if(!isfinite(m.m[i]))return false;return true;}
static bool finite_vertex(const kr3d_vertex *v){for(int i=0;i<3;i++)if(!isfinite(v->position[i])||!isfinite(v->normal[i]))return false;return isfinite(v->uv[0])&&isfinite(v->uv[1]);}
static float clamp01(float x){return x<0?0:x>1?1:x;}
static void unpack(uint32_t p,float c[4]){for(int i=0;i<4;i++)c[i]=(float)((p>>(i*8))&255u)/255.0f;}
static uint32_t pack(const float c[4]){uint32_t p=0;for(int i=0;i<4;i++)p|=(uint32_t)lroundf(clamp01(c[i])*255.0f)<<(i*8);return p;}
static void mul4(kr3d_mat4 m,float x,float y,float z,float w,float o[4]){o[0]=m.m[0]*x+m.m[4]*y+m.m[8]*z+m.m[12]*w;o[1]=m.m[1]*x+m.m[5]*y+m.m[9]*z+m.m[13]*w;o[2]=m.m[2]*x+m.m[6]*y+m.m[10]*z+m.m[14]*w;o[3]=m.m[3]*x+m.m[7]*y+m.m[11]*z+m.m[15]*w;}
static bool normal_matrix(kr3d_mat4 m,float out[9]){float a=m.m[0],b=m.m[4],c=m.m[8],d=m.m[1],f=m.m[9],g=m.m[2],h=m.m[6],i=m.m[10],ee=m.m[5];float det=a*(ee*i-f*h)-b*(d*i-f*g)+c*(d*h-ee*g);if(!isfinite(det)||fabsf(det)<1e-12f)return false;float inv=1.0f/det;out[0]=(ee*i-f*h)*inv;out[3]=(f*g-d*i)*inv;out[6]=(d*h-ee*g)*inv;out[1]=(c*h-b*i)*inv;out[4]=(a*i-c*g)*inv;out[7]=(b*g-a*h)*inv;out[2]=(b*f-c*ee)*inv;out[5]=(c*d-a*f)*inv;out[8]=(a*ee-b*d)*inv;return true;}
static kr3d_vec3 transform_normal(const float n[9],kr3d_vec3 v){return(kr3d_vec3){n[0]*v.x+n[3]*v.y+n[6]*v.z,n[1]*v.x+n[4]*v.y+n[7]*v.z,n[2]*v.x+n[5]*v.y+n[8]*v.z};}

bool kr3d_device_create(const kr3d_device_desc*d,kr3d_device**out,kr3d_error*e){if(out)*out=NULL;if(!d||!out||d->struct_size<sizeof*d||!d->max_meshes||!d->max_textures||!d->max_materials||!d->max_width||!d->max_height)return fail(e,KR3D_ERROR_ARGUMENT,"invalid device description");kr3d_device*x=calloc(1,sizeof*x);if(!x)return fail(e,KR3D_ERROR_MEMORY,"device allocation failed");x->meshes=calloc((size_t)d->max_meshes+1,sizeof* x->meshes);x->textures=calloc((size_t)d->max_textures+1,sizeof*x->textures);x->materials=calloc((size_t)d->max_materials+1,sizeof*x->materials);x->mw=d->max_width;x->mh=d->max_height;x->nm=d->max_meshes;x->nt=d->max_textures;x->nmat=d->max_materials;if(!x->meshes||!x->textures||!x->materials){kr3d_device_destroy(x);return fail(e,KR3D_ERROR_MEMORY,"resource table allocation failed");}*out=x;if(e)e->code=KR3D_OK;return true;}
void kr3d_device_destroy(kr3d_device*d){if(!d)return;for(uint32_t i=1;i<=d->nm;i++){free(d->meshes[i].v);free(d->meshes[i].i);}for(uint32_t i=1;i<=d->nt;i++)free(d->textures[i].p);free(d->owned_color);free(d->owned_depth);free(d->meshes);free(d->textures);free(d->materials);free(d);}
bool kr3d_mesh_create(kr3d_device*d,const kr3d_mesh_desc*s,kr3d_mesh_handle*out,kr3d_error*e){if(out)*out=0;if(!d||!s||!out||s->struct_size<sizeof*s||!s->vertices||!s->indices||s->vertex_count<3||s->index_count<3||s->index_count%3)return fail(e,KR3D_ERROR_ARGUMENT,"invalid indexed mesh");if(s->vertex_count>SIZE_MAX/sizeof(kr3d_vertex)||s->index_count>SIZE_MAX/sizeof(uint32_t))return fail(e,KR3D_ERROR_LIMIT,"mesh size overflow");for(size_t i=0;i<s->vertex_count;i++)if(!finite_vertex(&s->vertices[i]))return fail(e,KR3D_ERROR_ARGUMENT,"non-finite mesh vertex");for(size_t i=0;i<s->index_count;i++)if(s->indices[i]>=s->vertex_count)return fail(e,KR3D_ERROR_ARGUMENT,"mesh index out of range");uint32_t h=1;while(h<=d->nm&&d->meshes[h].v)h++;if(h>d->nm)return fail(e,KR3D_ERROR_LIMIT,"mesh limit reached");mesh*m=&d->meshes[h];m->v=malloc(s->vertex_count*sizeof*m->v);m->i=malloc(s->index_count*sizeof*m->i);if(!m->v||!m->i){free(m->v);free(m->i);memset(m,0,sizeof*m);return fail(e,KR3D_ERROR_MEMORY,"mesh allocation failed");}memcpy(m->v,s->vertices,s->vertex_count*sizeof*m->v);memcpy(m->i,s->indices,s->index_count*sizeof*m->i);m->nv=s->vertex_count;m->ni=s->index_count;*out=h;return true;}
void kr3d_mesh_destroy(kr3d_device*d,kr3d_mesh_handle h){if(!d||!h||h>d->nm)return;free(d->meshes[h].v);free(d->meshes[h].i);memset(&d->meshes[h],0,sizeof d->meshes[h]);}
bool kr3d_texture_create(kr3d_device*d,const kr3d_texture_desc*s,kr3d_texture_handle*out,kr3d_error*e){if(out)*out=0;if(!d||!s||!out||s->struct_size<sizeof*s||!s->rgba||!s->width||!s->height||s->width>d->mw||s->height>d->mh||(size_t)s->width>SIZE_MAX/(size_t)s->height/4u)return fail(e,KR3D_ERROR_ARGUMENT,"invalid texture");uint32_t h=1;while(h<=d->nt&&d->textures[h].p)h++;if(h>d->nt)return fail(e,KR3D_ERROR_LIMIT,"texture limit reached");size_t n=(size_t)s->width*s->height;texture*t=&d->textures[h];t->p=malloc(n*sizeof*t->p);if(!t->p)return fail(e,KR3D_ERROR_MEMORY,"texture allocation failed");memcpy(t->p,s->rgba,n*sizeof*t->p);t->w=s->width;t->h=s->height;t->filter=s->filter;t->au=s->address_u;t->av=s->address_v;*out=h;return true;}
void kr3d_texture_destroy(kr3d_device*d,kr3d_texture_handle h){if(!d||!h||h>d->nt)return;free(d->textures[h].p);memset(&d->textures[h],0,sizeof d->textures[h]);}
bool kr3d_material_create(kr3d_device*d,const kr3d_material_desc*s,kr3d_material_handle*out,kr3d_error*e){if(out)*out=0;if(!d||!s||!out||s->struct_size<sizeof*s||s->alpha_mode>KR3D_ALPHA_BLEND||!isfinite(s->alpha_cutoff)||s->alpha_cutoff<0||s->alpha_cutoff>1||(s->texture&&(s->texture>d->nt||!d->textures[s->texture].p)))return fail(e,KR3D_ERROR_ARGUMENT,"invalid material");uint32_t h=1;while(h<=d->nmat&&d->materials[h].rgba)h++;if(h>d->nmat)return fail(e,KR3D_ERROR_LIMIT,"material limit reached");d->materials[h]=(material){s->texture,s->rgba?s->rgba:0xffffffffu,s->flags,s->alpha_mode,s->alpha_cutoff};*out=h;return true;}
void kr3d_material_destroy(kr3d_device*d,kr3d_material_handle h){if(d&&h&&h<=d->nmat)memset(&d->materials[h],0,sizeof d->materials[h]);}
bool kr3d_frame_begin(kr3d_device*d,const kr3d_frame_desc*s,kr3d_error*e){if(!d||!s||s->struct_size<sizeof*s||d->frame||!s->width||!s->height||s->width>d->mw||s->height>d->mh||!finite_mat(s->view)||!finite_mat(s->projection)||!isfinite(s->ambient)||!isfinite(s->directional))return fail(e,KR3D_ERROR_ARGUMENT,"invalid frame");size_t n=(size_t)s->width*s->height;if(!s->color){uint32_t*p=realloc(d->owned_color,n*sizeof*p);if(!p)return fail(e,KR3D_ERROR_MEMORY,"color target allocation failed");d->owned_color=p;}if(!s->depth){float*p=realloc(d->owned_depth,n*sizeof*p);if(!p)return fail(e,KR3D_ERROR_MEMORY,"depth target allocation failed");d->owned_depth=p;}d->f=*s;d->f.color=s->color?s->color:d->owned_color;d->f.depth=s->depth?s->depth:d->owned_depth;for(size_t i=0;i<n;i++){d->f.color[i]=s->clear_rgba;d->f.depth[i]=1.0f;}d->submitted=d->rasterized=d->pixels=0;d->frame=true;return true;}

static float plane_dist(const cv*v,int p){switch(p){case 0:return v->w+v->x;case 1:return v->w-v->x;case 2:return v->w+v->y;case 3:return v->w-v->y;case 4:return v->w+v->z;default:return v->w-v->z;}}
static cv lerp_cv(cv a,cv b,float t){cv r;float*o=&r.x,*x=&a.x,*y=&b.x;for(size_t i=0;i<sizeof(cv)/sizeof(float);i++)o[i]=x[i]+(y[i]-x[i])*t;return r;}
static int clip_plane(const cv*in,int n,cv*out,int p){int k=0;cv a=in[n-1];float da=plane_dist(&a,p);for(int i=0;i<n;i++){cv b=in[i];float db=plane_dist(&b,p);bool ia=da>=0,ib=db>=0;if(ia!=ib){float t=da/(da-db);out[k++]=lerp_cv(a,b,t);}if(ib)out[k++]=b;a=b;da=db;}return k;}
static float wrap(float x,kr3d_address a){if(a==KR3D_ADDRESS_REPEAT){x=x-floorf(x);if(x<0)x+=1;}return clamp01(x);}
static void sample(const texture*t,float u,float v,float out[4]){if(!t){out[0]=out[1]=out[2]=out[3]=1;return;}u=wrap(u,t->au);v=wrap(v,t->av);float x=u*(float)(t->w-1),y=v*(float)(t->h-1);if(t->filter==KR3D_FILTER_NEAREST){unpack(t->p[(size_t)lroundf(y)*t->w+(size_t)lroundf(x)],out);return;}uint32_t x0=(uint32_t)floorf(x),y0=(uint32_t)floorf(y),x1=x0+1<t->w?x0+1:x0,y1=y0+1<t->h?y0+1:y0;float fx=x-(float)x0,fy=y-(float)y0,c[4][4];unpack(t->p[(size_t)y0*t->w+x0],c[0]);unpack(t->p[(size_t)y0*t->w+x1],c[1]);unpack(t->p[(size_t)y1*t->w+x0],c[2]);unpack(t->p[(size_t)y1*t->w+x1],c[3]);for(int i=0;i<4;i++)out[i]=(c[0][i]*(1-fx)+c[1][i]*fx)*(1-fy)+(c[2][i]*(1-fx)+c[3][i]*fx)*fy;}
static float edge(float ax,float ay,float bx,float by,float x,float y){return (x-ax)*(by-ay)-(y-ay)*(bx-ax);}
static void raster(kr3d_device*d,cv a,cv b,cv c,const material*m){float fw=(float)d->f.width,fh=(float)d->f.height;float ax=(a.x/a.w*.5f+.5f)*fw,ay=(1-(a.y/a.w*.5f+.5f))*fh,bx=(b.x/b.w*.5f+.5f)*fw,by=(1-(b.y/b.w*.5f+.5f))*fh,cx=(c.x/c.w*.5f+.5f)*fw,cy=(1-(c.y/c.w*.5f+.5f))*fh;float area=edge(ax,ay,bx,by,cx,cy);if(fabsf(area)<1e-8f||(!(m->flags&KR3D_MATERIAL_TWO_SIDED)&&area>=0))return;int minx=(int)floorf(fminf(ax,fminf(bx,cx))),maxx=(int)ceilf(fmaxf(ax,fmaxf(bx,cx))),miny=(int)floorf(fminf(ay,fminf(by,cy))),maxy=(int)ceilf(fmaxf(ay,fmaxf(by,cy)));if(minx<0)minx=0;if(miny<0)miny=0;if(maxx>=(int)d->f.width)maxx=(int)d->f.width-1;if(maxy>=(int)d->f.height)maxy=(int)d->f.height-1;float ia=1/a.w,ib=1/b.w,ic=1/c.w,mc[4];unpack(m->rgba,mc);texture*t=m->tex?&d->textures[m->tex]:NULL;d->rasterized++;for(int y=miny;y<=maxy;y++)for(int x=minx;x<=maxx;x++){float w0=edge(bx,by,cx,cy,(float)x+.5f,(float)y+.5f)/area,w1=edge(cx,cy,ax,ay,(float)x+.5f,(float)y+.5f)/area,w2=1-w0-w1;if(w0<0||w1<0||w2<0)continue;float q=w0*ia+w1*ib+w2*ic;if(fabsf(q)<1e-20f)continue;float z=(w0*a.z*ia+w1*b.z*ib+w2*c.z*ic)*.5f+.5f;size_t at=(size_t)y*(size_t)d->f.width+(size_t)x;if(z<0||z>1||z>=d->f.depth[at])continue;float u=(w0*a.u*ia+w1*b.u*ib+w2*c.u*ic)/q,v=(w0*a.v*ia+w1*b.v*ib+w2*c.v*ic)/q,nx=(w0*a.n.x*ia+w1*b.n.x*ib+w2*c.n.x*ic)/q,ny=(w0*a.n.y*ia+w1*b.n.y*ib+w2*c.n.y*ic)/q,nz=(w0*a.n.z*ia+w1*b.n.z*ib+w2*c.n.z*ic)/q;float tc[4],vc[4],src[4];sample(t,u,v,tc);for(int k=0;k<4;k++)vc[k]=(w0*a.c[k]*ia+w1*b.c[k]*ib+w2*c.c[k]*ic)/q;kr3d_vec3 n={nx,ny,nz},ld=d->f.light_direction;float lit=1;if(!(m->flags&(KR3D_MATERIAL_UNLIT|KR3D_MATERIAL_EMISSIVE))){if(!kr3d_vec3_normalize(n,&n)||!kr3d_vec3_normalize(ld,&ld))lit=d->f.ambient;else lit=d->f.ambient+d->f.directional*fmaxf(0,-kr3d_vec3_dot(n,ld));}for(int k=0;k<3;k++)src[k]=tc[k]*vc[k]*mc[k]*lit;src[3]=tc[3]*vc[3]*mc[3];if(m->alpha==KR3D_ALPHA_TEST&&src[3]<m->cutoff)continue;if(m->alpha==KR3D_ALPHA_BLEND){float dst[4];unpack(d->f.color[at],dst);for(int k=0;k<3;k++)src[k]=src[k]*src[3]+dst[k]*(1-src[3]);src[3]=src[3]+dst[3]*(1-src[3]);}else d->f.depth[at]=z;d->f.color[at]=pack(src);d->pixels++;}}
bool kr3d_draw(kr3d_device*d,const kr3d_draw_desc*s,kr3d_error*e){if(!d||!s||s->struct_size<sizeof*s||!d->frame||!s->mesh||s->mesh>d->nm||!d->meshes[s->mesh].v||!s->material||s->material>d->nmat||!d->materials[s->material].rgba||!finite_mat(s->model))return fail(e,KR3D_ERROR_STATE,"invalid draw");mesh*m=&d->meshes[s->mesh];material*mat=&d->materials[s->material];float normal[9]={1,0,0,0,1,0,0,0,1};bool lit=!(mat->flags&(KR3D_MATERIAL_UNLIT|KR3D_MATERIAL_EMISSIVE));if(lit&&!normal_matrix(s->model,normal))return fail(e,KR3D_ERROR_ARGUMENT,"singular model normal matrix");kr3d_mat4 mv=kr3d_mat4_mul(d->f.view,s->model),mvp=kr3d_mat4_mul(d->f.projection,mv);for(size_t q=0;q<m->ni;q+=3){cv p[12],a[12],b[12];for(int k=0;k<3;k++){kr3d_vertex*v=&m->v[m->i[q+(size_t)k]];float z[4];kr3d_vec3 source={v->normal[0],v->normal[1],v->normal[2]};mul4(mvp,v->position[0],v->position[1],v->position[2],1,z);p[k]=(cv){z[0],z[1],z[2],z[3],v->uv[0],v->uv[1],lit?transform_normal(normal,source):source,{0}};unpack(v->color_rgba,p[k].c);}int n=3;cv*in=p,*out=a;for(int plane=0;plane<6&&n;plane++){n=clip_plane(in,n,out,plane);cv*tmp=in;in=out;out=(tmp==p)?b:(tmp==a?p:a);}d->submitted++;for(int k=1;k+1<n;k++)raster(d,in[0],in[k],in[k+1],mat);}return true;}
bool kr3d_frame_end(kr3d_device*d,kr3d_frame_result*r,kr3d_error*e){if(!d||!d->frame||!r||r->struct_size<sizeof*r)return fail(e,KR3D_ERROR_STATE,"no active frame or invalid result");r->color=d->f.color;r->depth=d->f.depth;r->width=d->f.width;r->height=d->f.height;r->submitted_triangles=d->submitted;r->rasterized_triangles=d->rasterized;r->shaded_pixels=d->pixels;d->frame=false;return true;}
