#!/usr/bin/env python3
"""Pack, verify and embed kilix-game-kit policy blobs (format v1).

    kilix_policy.py pack --widths 11 64 64 3 [--temperature T] RAW.f32 OUT.kxpol
    kilix_policy.py verify BLOB.kxpol
    kilix_policy.py embed BLOB.kxpol --symbol NAME OUT.h [--check]

RAW.f32 holds little-endian float32 parameters, layer by layer, weights
[out][in] then biases [out] -- the order torch.nn.Sequential(Linear, ...)
state_dict() values flatten to. `embed --check` fails if OUT.h differs from a
fresh rendering, so a checked-in header cannot drift from its blob. Standard
library only; the C loader in src/kilix_game_policy.c is the reference.
"""
import argparse
import hashlib
import json
import math
import struct
import sys

MAGIC = b"KXPOLICY"
VERSION = 1
MAX_LAYERS = 8
MAX_WIDTH = 256


def fnv1a64(data: bytes) -> int:
    value = 1469598103934665603
    for byte in data:
        value ^= byte
        value = (value * 1099511628211) & 0xFFFFFFFFFFFFFFFF
    return value


def parameter_count(widths):
    return sum(widths[i] * widths[i - 1] + widths[i] for i in range(1, len(widths)))


def pack(widths, parameters: bytes, temperature: float = 1.0) -> bytes:
    layers = len(widths) - 1
    if not 1 <= layers <= MAX_LAYERS or any(not 1 <= w <= MAX_WIDTH for w in widths):
        raise ValueError(f"shape out of bounds: {widths}")
    if len(parameters) != 4 * parameter_count(widths):
        raise ValueError(f"expected {4 * parameter_count(widths)} parameter bytes, got {len(parameters)}")
    if not (math.isfinite(temperature) and temperature > 0):
        raise ValueError("temperature must be finite and positive")
    values = struct.unpack(f"<{len(parameters) // 4}f", parameters)
    if not all(math.isfinite(v) for v in values):
        raise ValueError("non-finite parameter")
    body = (MAGIC + struct.pack("<II", VERSION, layers) +
            struct.pack(f"<{len(widths)}I", *widths) +
            struct.pack("<f", temperature) + parameters)
    return body + struct.pack("<Q", fnv1a64(body))


def inspect(blob: bytes) -> dict:
    if len(blob) < 16 or blob[:8] != MAGIC:
        raise ValueError("not a policy blob")
    version, layers = struct.unpack_from("<II", blob, 8)
    if version != VERSION:
        raise ValueError(f"unsupported version {version}")
    if not 1 <= layers <= MAX_LAYERS:
        raise ValueError("layer count out of bounds")
    widths = list(struct.unpack_from(f"<{layers + 1}I", blob, 16))
    header = 16 + 4 * (layers + 1) + 4
    expected = header + 4 * parameter_count(widths) + 8
    if len(blob) != expected:
        raise ValueError(f"size {len(blob)} != expected {expected}")
    (temperature,) = struct.unpack_from("<f", blob, header - 4)
    (stored,) = struct.unpack_from("<Q", blob, expected - 8)
    if fnv1a64(blob[:-8]) != stored:
        raise ValueError("digest mismatch")
    return {"version": version, "widths": widths, "parameters": parameter_count(widths),
            "temperature": temperature, "bytes": len(blob), "fnv1a64": f"{stored:016x}",
            "sha256": hashlib.sha256(blob).hexdigest()}


def render_header(blob: bytes, symbol: str) -> str:
    info = inspect(blob)
    if not symbol.isidentifier():
        raise ValueError(f"bad C identifier {symbol!r}")
    lines = [
        "/* Generated by kilix-game-kit tools/kilix_policy.py embed; do not edit. */",
        f"/* widths {' '.join(map(str, info['widths']))}, {info['parameters']} parameters, "
        f"sha256 {info['sha256']} */",
        f"#ifndef {symbol.upper()}_H",
        f"#define {symbol.upper()}_H",
        "",
        "#include <stddef.h>",
        "#include <stdint.h>",
        "",
        f"#define {symbol.upper()}_FNV1A64 UINT64_C(0x{info['fnv1a64']})",
        f"static const size_t {symbol}_size = {len(blob)}u;",
        f"static const uint8_t {symbol}[{len(blob)}] = {{",
    ]
    for offset in range(0, len(blob), 16):
        chunk = blob[offset:offset + 16]
        lines.append("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
    lines += ["};", "", "#endif", ""]
    return "\n".join(lines)


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    sub = parser.add_subparsers(dest="command", required=True)
    p = sub.add_parser("pack")
    p.add_argument("--widths", type=int, nargs="+", required=True)
    p.add_argument("--temperature", type=float, default=1.0)
    p.add_argument("raw")
    p.add_argument("out")
    v = sub.add_parser("verify")
    v.add_argument("blob")
    e = sub.add_parser("embed")
    e.add_argument("blob")
    e.add_argument("--symbol", required=True)
    e.add_argument("out")
    e.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    try:
        if args.command == "pack":
            with open(args.raw, "rb") as fh:
                blob = pack(args.widths, fh.read(), args.temperature)
            with open(args.out, "wb") as fh:
                fh.write(blob)
            print(json.dumps(inspect(blob)))
        elif args.command == "verify":
            with open(args.blob, "rb") as fh:
                print(json.dumps(inspect(fh.read())))
        else:
            with open(args.blob, "rb") as fh:
                text = render_header(fh.read(), args.symbol)
            if args.check:
                try:
                    with open(args.out, encoding="utf-8") as fh:
                        current = fh.read()
                except FileNotFoundError:
                    current = None
                if current != text:
                    print(f"{args.out}: stale; regenerate with kilix_policy.py embed", file=sys.stderr)
                    return 1
                print(f"ok: {args.out} matches {args.blob}")
            else:
                with open(args.out, "w", encoding="utf-8") as fh:
                    fh.write(text)
    except (OSError, ValueError, struct.error) as error:
        print(f"kilix_policy: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
