ifndef KILIX_ASSETS_MK_INCLUDED
KILIX_ASSETS_MK_INCLUDED := 1

KILIX_ASSETS_DIR ?= third_party/kilix-assets
KILIX_ASSETS_ROOT := $(abspath $(KILIX_ASSETS_DIR))
KILIX_ASSETS_BUILD_DIR ?= $(KILIX_ASSETS_ROOT)/build
KILIX_ASSETS_LIB := $(KILIX_ASSETS_BUILD_DIR)/libkilix-assets.a
KILIX_ASSETS_CPPFLAGS := -I$(KILIX_ASSETS_ROOT)/include
KILIX_ASSETS_LDLIBS := -lz
KILIX_ASSETS_INPUTS := $(KILIX_ASSETS_ROOT)/Makefile \
	$(wildcard $(KILIX_ASSETS_ROOT)/include/*.h) \
	$(wildcard $(KILIX_ASSETS_ROOT)/src/*.c)

$(KILIX_ASSETS_LIB): $(KILIX_ASSETS_INPUTS)
	$(MAKE) -C $(KILIX_ASSETS_ROOT) BUILD_DIR=$(KILIX_ASSETS_BUILD_DIR) all

endif
