ifndef KILIX_TACTICS_DIR
KILIX_TACTICS_DIR := third_party/kilix-tactics-engine
endif

KILIX_TACTICS_ROOT := $(abspath $(KILIX_TACTICS_DIR))
KILIX_TACTICS_BUILD_DIR ?= $(KILIX_TACTICS_ROOT)/build
KILIX_TACTICS_BUILD_ROOT := $(abspath $(KILIX_TACTICS_BUILD_DIR))

# Prefer the rasterizer the including project already pinned, so the soft
# adapter never compiles a second copy of soft-raster.
ifneq ($(strip $(SOFT_RASTER_DIR)),)
KILIX_TACTICS_SOFT_RASTER_ROOT := $(abspath $(SOFT_RASTER_DIR))
else
KILIX_TACTICS_SOFT_RASTER_ROOT := $(KILIX_TACTICS_ROOT)/third_party/soft-raster
endif

KILIX_TACTICS_CORE_LIB := $(KILIX_TACTICS_BUILD_ROOT)/libkilix-tactics-core.a
KILIX_TACTICS_SOFT_LIB := $(KILIX_TACTICS_BUILD_ROOT)/libkilix-tactics-soft.a
KILIX_TACTICS_LIBS := $(KILIX_TACTICS_SOFT_LIB) $(KILIX_TACTICS_CORE_LIB)
KILIX_TACTICS_CPPFLAGS := -I$(KILIX_TACTICS_ROOT)/include
KILIX_TACTICS_PUBLIC_HEADERS := $(wildcard $(KILIX_TACTICS_ROOT)/include/*.h)

KILIX_TACTICS_CORE_INPUTS := \
	$(KILIX_TACTICS_ROOT)/src/types.c \
	$(KILIX_TACTICS_ROOT)/src/map.c \
	$(KILIX_TACTICS_ROOT)/src/projection.c \
	$(KILIX_TACTICS_ROOT)/src/nav.c \
	$(KILIX_TACTICS_ROOT)/src/sight.c \
	$(KILIX_TACTICS_ROOT)/src/render_queue.c \
	$(KILIX_TACTICS_PUBLIC_HEADERS) \
	$(KILIX_TACTICS_ROOT)/Makefile

KILIX_TACTICS_SOFT_INPUTS := \
	$(KILIX_TACTICS_ROOT)/src/render_soft.c \
	$(KILIX_TACTICS_PUBLIC_HEADERS) \
	$(KILIX_TACTICS_SOFT_RASTER_ROOT)/include/soft_raster.h \
	$(KILIX_TACTICS_ROOT)/Makefile

$(KILIX_TACTICS_CORE_LIB): $(KILIX_TACTICS_CORE_INPUTS)
	$(MAKE) -C $(KILIX_TACTICS_ROOT) \
		BUILD_DIR="$(KILIX_TACTICS_BUILD_ROOT)" \
		SOFT_RASTER_DIR="$(KILIX_TACTICS_SOFT_RASTER_ROOT)" "$@"

$(KILIX_TACTICS_SOFT_LIB): $(KILIX_TACTICS_CORE_LIB) $(KILIX_TACTICS_SOFT_INPUTS)
	$(MAKE) -C $(KILIX_TACTICS_ROOT) \
		BUILD_DIR="$(KILIX_TACTICS_BUILD_ROOT)" \
		SOFT_RASTER_DIR="$(KILIX_TACTICS_SOFT_RASTER_ROOT)" "$@"
