#include "kr3d.h"
#include <assert.h>
#include <math.h>
#include <stdio.h>
#include <string.h>

static void math_tests(void){kr3d_vec3 n;assert(kr3d_vec3_normalize((kr3d_vec3){3,0,0},&n));assert(fabsf(n.x-1)<1e-6f);assert(!kr3d_vec3_normalize((kr3d_vec3){0,0,0},&n));kr3d_mat4 p,v;assert(kr3d_mat4_perspective(1.0f,1,0.1f,100,&p));assert(!kr3d_mat4_perspective(1,0,1,2,&p));assert(kr3d_mat4_look_at((kr3d_vec3){0,0,2},(kr3d_vec3){0,0,0},(kr3d_vec3){0,1,0},&v));kr3d_vec3 q;assert(kr3d_mat4_transform_point(v,(kr3d_vec3){0,0,0},&q));assert(fabsf(q.z+2)<1e-6f);kr3d_quat r;assert(kr3d_quat_axis_angle((kr3d_vec3){0,1,0},3.1415926f,&r));kr3d_mat4 m=kr3d_mat4_from_quat(r);kr3d_vec3 x=kr3d_mat4_transform_vector(m,(kr3d_vec3){1,0,0});assert(x.x<-.999f);}
static void renderer_test(void){kr3d_device*d=NULL;kr3d_error e={0};kr3d_device_desc dd={sizeof dd,8,8,8,64,64};assert(kr3d_device_create(&dd,&d,&e));kr3d_vertex vv[]={{{-1,-1,0},{0,0,1},{0,1},0xffffffffu},{{1,-1,0},{0,0,1},{1,1},0xffffffffu},{{0,1,0},{0,0,1},{.5f,0},0xffffffffu}};uint32_t ii[]={0,1,2};kr3d_mesh_handle mh=0;kr3d_mesh_desc md={sizeof md,vv,3,ii,3};assert(kr3d_mesh_create(d,&md,&mh,&e));uint32_t texels[]={0xff0000ffu,0xff00ff00u,0xffff0000u,0xffffffffu};kr3d_texture_handle th=0;kr3d_texture_desc td={sizeof td,2,2,texels,KR3D_FILTER_BILINEAR,KR3D_ADDRESS_CLAMP,KR3D_ADDRESS_CLAMP};assert(kr3d_texture_create(d,&td,&th,&e));kr3d_material_handle mat=0;kr3d_material_desc ad={sizeof ad,th,0xffffffffu,KR3D_MATERIAL_TWO_SIDED|KR3D_MATERIAL_UNLIT,KR3D_ALPHA_OPAQUE,.5f,1,0};assert(kr3d_material_create(d,&ad,&mat,&e));uint32_t color[64*64];float depth[64*64];kr3d_mat4 proj,view;assert(kr3d_mat4_perspective(1.2f,1,.1f,20,&proj));assert(kr3d_mat4_look_at((kr3d_vec3){0,0,3},(kr3d_vec3){0,0,0},(kr3d_vec3){0,1,0},&view));kr3d_frame_desc fd={sizeof fd,64,64,color,depth,0x11223344u,view,proj,{0,0,-1},.2f,.8f};assert(kr3d_frame_begin(d,&fd,&e));kr3d_draw_desc draw={sizeof draw,mh,mat,{{1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1}}};assert(kr3d_draw(d,&draw,&e));kr3d_frame_result fr={.struct_size=sizeof fr};assert(kr3d_frame_end(d,&fr,&e));assert(fr.submitted_triangles==1);assert(fr.rasterized_triangles>=1);assert(fr.shaded_pixels>100);assert(color[32u*64u+32u]!=0x11223344u);assert(depth[32u*64u+32u]<1);kr3d_material_handle lit=0;ad.flags=KR3D_MATERIAL_TWO_SIDED;assert(kr3d_material_create(d,&ad,&lit,&e));assert(kr3d_frame_begin(d,&fd,&e));draw.material=lit;draw.model=kr3d_mat4_scale((kr3d_vec3){1,1,0});assert(!kr3d_draw(d,&draw,&e)&&e.code==KR3D_ERROR_ARGUMENT);assert(kr3d_frame_end(d,&fr,&e));uint32_t bad[]={0,1,9};md.indices=bad;mh=123;assert(!kr3d_mesh_create(d,&md,&mh,&e)&&mh==0&&e.code==KR3D_ERROR_ARGUMENT);kr3d_mesh_destroy(d,0);kr3d_device_destroy(d);}
static void texture_update_test(void){kr3d_device*d=NULL;kr3d_error e={0};kr3d_device_desc dd={sizeof dd,1,1,1,8,8};assert(kr3d_device_create(&dd,&d,&e));uint32_t pixels[16]={0};kr3d_texture_desc td={sizeof td,4,4,pixels,KR3D_FILTER_NEAREST,KR3D_ADDRESS_CLAMP,KR3D_ADDRESS_CLAMP,0,NULL};kr3d_texture_handle h=0;assert(kr3d_texture_create(d,&td,&h,&e));uint32_t patch[4]={1,2,3,4};kr3d_texture_update_desc u={sizeof u,1,1,2,2,patch,0};assert(kr3d_texture_update(d,h,&u,&e)&&e.code==KR3D_OK);u.x=3;assert(!kr3d_texture_update(d,h,&u,&e)&&e.code==KR3D_ERROR_ARGUMENT);u.x=1;u.rgba=NULL;assert(!kr3d_texture_update(d,h,&u,&e)&&e.code==KR3D_ERROR_ARGUMENT);u.rgba=patch;assert(!kr3d_texture_update(d,0,&u,&e)&&e.code==KR3D_ERROR_ARGUMENT);kr3d_texture_destroy(d,h);assert(!kr3d_texture_update(d,h,&u,&e)&&e.code==KR3D_ERROR_ARGUMENT);kr3d_device_destroy(d);}
static void mip_test(void){kr3d_device*d=NULL;kr3d_error e={0};kr3d_device_desc dd={sizeof dd,1,2,1,16,16};uint32_t chain[64+16+4+1];for(size_t i=0;i<64;i++)chain[i]=0xff0000ffu;for(size_t i=64;i<80;i++)chain[i]=0xff00ff00u;for(size_t i=80;i<84;i++)chain[i]=0xffff0000u;chain[84]=0xffffffffu;assert(kr3d_device_create(&dd,&d,&e));kr3d_texture_desc td={sizeof td,8,8,chain,KR3D_FILTER_NEAREST,KR3D_ADDRESS_CLAMP,KR3D_ADDRESS_CLAMP,4,chain};kr3d_texture_handle tex=0,bad=0;assert(kr3d_texture_create(d,&td,&tex,&e));td.mip_count=5;assert(!kr3d_texture_create(d,&td,&bad,&e)&&e.code==KR3D_ERROR_ARGUMENT);td.mip_count=4;td.mip_rgba=NULL;assert(!kr3d_texture_create(d,&td,&bad,&e)&&e.code==KR3D_ERROR_ARGUMENT);uint32_t white=0xff808080u;kr3d_texture_update_desc up={sizeof up,0,0,1,1,&white,3};assert(kr3d_texture_update(d,tex,&up,&e));up.width=2;assert(!kr3d_texture_update(d,tex,&up,&e)&&e.code==KR3D_ERROR_ARGUMENT);up.width=1;up.mip_level=4;assert(!kr3d_texture_update(d,tex,&up,&e)&&e.code==KR3D_ERROR_ARGUMENT);kr3d_texture_destroy(d,tex);kr3d_device_destroy(d);}
int main(void){math_tests();renderer_test();texture_update_test();mip_test();puts("kilix-render-3d: all tests passed");return 0;}
