ifndef KILIX_VALVE_CLIENT_MK_INCLUDED
KILIX_VALVE_CLIENT_MK_INCLUDED := 1
KILIX_VALVE_CLIENT_DEFAULT_GOAL_BEFORE_INCLUDE := $(.DEFAULT_GOAL)

KILIX_VALVE_CLIENT_DIR ?= third_party/kilix-valve-client
KILIX_VALVE_CLIENT_ROOT := $(abspath $(KILIX_VALVE_CLIENT_DIR))
KILIX_VALVE_CLIENT_BUILD_DIR ?= $(KILIX_VALVE_CLIENT_ROOT)/build
KILIX_VALVE_CLIENT_LIB := \
	$(KILIX_VALVE_CLIENT_BUILD_DIR)/libkilix-valve-client.a
KILIX_VALVE_CLIENT_CPPFLAGS := -I$(KILIX_VALVE_CLIENT_ROOT)/include
KILIX_VALVE_CLIENT_INPUTS := $(KILIX_VALVE_CLIENT_ROOT)/Makefile \
	$(wildcard $(KILIX_VALVE_CLIENT_ROOT)/include/*.h) \
	$(wildcard $(KILIX_VALVE_CLIENT_ROOT)/src/*.c) \
	$(wildcard $(KILIX_VALVE_CLIENT_ROOT)/src/*.h)

$(KILIX_VALVE_CLIENT_LIB): $(KILIX_VALVE_CLIENT_INPUTS)
	$(MAKE) -C $(KILIX_VALVE_CLIENT_ROOT) \
		BUILD_DIR=$(KILIX_VALVE_CLIENT_BUILD_DIR) all

ifeq ($(KILIX_VALVE_CLIENT_DEFAULT_GOAL_BEFORE_INCLUDE),)
.DEFAULT_GOAL :=
endif

endif
