KILIX_RENDER_3D_DEFAULT_GOAL_BEFORE_INCLUDE := $(.DEFAULT_GOAL)
ifndef KILIX_RENDER_3D_MK_INCLUDED
KILIX_RENDER_3D_MK_INCLUDED := 1
KILIX_RENDER_3D_DIR ?= third_party/kilix-game-sdk/kilix-render-3d
KILIX_RENDER_3D_BUILD_DIR ?= $(KILIX_RENDER_3D_DIR)/build
KILIX_RENDER_3D_LIB := $(KILIX_RENDER_3D_BUILD_DIR)/libkilix-render-3d.a
KILIX_RENDER_3D_CPPFLAGS := -I$(KILIX_RENDER_3D_DIR)/include
KILIX_RENDER_3D_LDLIBS := -lm
$(KILIX_RENDER_3D_LIB):
	$(MAKE) -C $(KILIX_RENDER_3D_DIR) BUILD_DIR=$(abspath $(KILIX_RENDER_3D_BUILD_DIR)) all
endif
ifeq ($(KILIX_RENDER_3D_DEFAULT_GOAL_BEFORE_INCLUDE),)
.DEFAULT_GOAL :=
endif
