KILIX_STORY_DEFAULT_GOAL_BEFORE_INCLUDE := $(.DEFAULT_GOAL)

ifndef KILIX_STORY_ROOT
KILIX_STORY_ROOT := $(abspath $(dir $(lastword $(MAKEFILE_LIST)))/..)
endif
KILIX_STORY_BUILD_DIR ?= $(KILIX_STORY_ROOT)/build
KILIX_STORY_LIB := $(KILIX_STORY_BUILD_DIR)/libkilix-story.a
KILIX_STORY_CPPFLAGS := -I$(KILIX_STORY_ROOT)/include

$(KILIX_STORY_LIB): \
		$(KILIX_STORY_ROOT)/Makefile \
		$(KILIX_STORY_ROOT)/include/kilix_story.h \
		$(KILIX_STORY_ROOT)/src/kilix_story.c
	$(MAKE) -C $(KILIX_STORY_ROOT) \
		BUILD_DIR=$(KILIX_STORY_BUILD_DIR) $(KILIX_STORY_LIB)

ifeq ($(KILIX_STORY_DEFAULT_GOAL_BEFORE_INCLUDE),)
.DEFAULT_GOAL :=
endif
